# Generated by Django 2.2.6 on 2019-10-31 23:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('display_name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('public_description', models.CharField(max_length=256)),
                ('created_utc', models.BigIntegerField()),
                ('subscribers', models.PositiveIntegerField(verbose_name='subscribers count')),
                ('over18', models.BooleanField(verbose_name='NSFW')),
            ],
        ),
    ]
