# Generated by Django 2.2.6 on 2019-11-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.CharField(help_text='The ID of the subreddit.', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Fullname of the subreddit.', max_length=256)),
                ('display_name', models.CharField(help_text='Name of the subreddit.', max_length=256)),
                ('description', models.TextField(help_text='Subreddit description, in Markdown.', null=True)),
                ('description_html', models.TextField(help_text='Subreddit description, in HTML.', null=True)),
                ('public_description', models.TextField(help_text='Description of the subreddit, shown in searches and on the"You must be invited to visit this community"page(if applicable).', null=True)),
                ('created_utc', models.DateTimeField(help_text='Time the subreddit was created, from Unix Time to Datetime format.')),
                ('subscribers', models.PositiveIntegerField(default=0, help_text='Count of subscribers.', verbose_name='subscribers count')),
                ('spoilers_enabled', models.BooleanField(help_text='Whether the spoiler tag feature is enabled.', null=True)),
                ('over18', models.BooleanField(help_text='Whether the subreddit is NSFW.', null=True, verbose_name='nsfw')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Subreddits',
                'ordering': ['name'],
                'get_latest_by': ['created_at'],
            },
        ),
    ]
