# Generated by Django 2.2.6 on 2019-12-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='can_assign_link_flair',
            field=models.BooleanField(help_text='Whether users can assign their own link flair.', null=True),
        ),
        migrations.AddField(
            model_name='subreddit',
            name='can_assign_user_flair',
            field=models.BooleanField(help_text='Whether users can assign their own user flair.', null=True),
        ),
    ]
