# Generated by Django 2.2.6 on 2019-12-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('subreddits', '0002_auto_20191202_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='clients',
            field=models.ManyToManyField(to='clients.ClientOrg'),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='name',
            field=models.CharField(db_index=True, help_text='Fullname of the subreddit.', max_length=256),
        ),
    ]
