# Generated by Django 2.2.6 on 2019-12-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddits', '0003_auto_20191203_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='display_name',
            field=models.CharField(db_index=True, help_text='Name of the subreddit.', max_length=256),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='name',
            field=models.CharField(help_text='Fullname of the subreddit.', max_length=256),
        ),
    ]
