# Generated by Django 2.2.6 on 2019-12-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddits', '0004_auto_20191203_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='description',
            field=models.TextField(blank=True, help_text='Subreddit description, in Markdown.', null=True),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='description_html',
            field=models.TextField(blank=True, help_text='Subreddit description, in HTML.', null=True),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='public_description',
            field=models.TextField(blank=True, help_text='Description of the subreddit, shown in searches and on the"You must be invited to visit this community"page(if applicable).', null=True),
        ),
    ]
