# Generated by Django 2.2.6 on 2019-11-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redditor',
            fields=[
                ('id', models.CharField(help_text='The ID of the Redditor.', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='The Redditor’s username.', max_length=256)),
                ('created_utc', models.DateTimeField(help_text='Time the account was created, represented in Unix Time.')),
                ('has_verified_email', models.BooleanField(default=False, help_text='Whether or not the Redditor has verified their email.')),
                ('icon_img', models.URLField(help_text='The url of the Redditors’ avatar.')),
                ('comment_karma', models.IntegerField(default=0, help_text='The comment karma for the Redditor.')),
                ('link_karma', models.IntegerField(default=0, help_text='The link karma for the Redditor.')),
                ('is_employee', models.BooleanField(help_text='Whether or not the Redditor is a Reddit employee.', null=True)),
                ('is_friend', models.BooleanField(help_text='Whether or not the Redditor is friends with the authenticated user.', null=True)),
                ('is_mod', models.BooleanField(help_text='Whether or not the Redditor mods any subreddits.', null=True)),
                ('is_gold', models.BooleanField(help_text='Whether or not the Redditor has active gold status.', null=True)),
            ],
            options={
                'ordering': ['name', 'created_utc'],
            },
        ),
    ]
