# Generated by Django 2.2.6 on 2019-11-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditor',
            name='num_friends',
            field=models.PositiveIntegerField(default=0, help_text='Count of friends.', verbose_name='friends count'),
        ),
    ]
