# Generated by Django 2.2.6 on 2019-12-01 16:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('redditors', '0002_redditor_num_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disconnected_at', models.DateTimeField(null=True)),
                ('last_client_request_at', models.DateTimeField(null=True)),
                ('last_client_update_at', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reddit_token', encrypted_model_fields.fields.EncryptedCharField(help_text='Reddit refresh token for the Salesforce Client Org.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('redditor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clients_orgs', to='redditors.Redditor')),
            ],
            options={
                'verbose_name_plural': 'Salesforce Organizations Clients',
                'ordering': ['updated_at'],
                'get_latest_by': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesforceOrg',
            fields=[
                ('org_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=256)),
                ('org_url', models.URLField(max_length=512)),
                ('package_version', models.CharField(blank=True, default='1.0', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Salesforce Organizations',
                'ordering': ['org_name'],
                'get_latest_by': 'created_date',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('client_org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='clients.ClientOrg', verbose_name='Client Org')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.AddField(
            model_name='clientorg',
            name='salesforce_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='clients.SalesforceOrg'),
        ),
    ]
