# Generated by Django 2.2.6 on 2020-01-08 20:49

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforceorg',
            name='access_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Salesforce connected app oauth access token.'),
        ),
        migrations.AddField(
            model_name='salesforceorg',
            name='instance_url',
            field=models.URLField(blank=True, max_length=512),
        ),
    ]
