# Generated by Django 2.2.6 on 2020-01-08 21:05

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20200108_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesforceorg',
            name='access_token',
            field=encrypted_model_fields.fields.EncryptedCharField(help_text='Salesforce connected app oauth access token.', null=True),
        ),
    ]
