# Generated by Django 2.2.6 on 2020-01-14 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200108_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesforceorg',
            name='org_url',
        ),
    ]
