# Generated by Django 2.2.6 on 2020-01-15 18:22

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_salesforceorg_org_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforceorg',
            name='refresh_token',
            field=encrypted_model_fields.fields.EncryptedCharField(help_text='Salesforce connected app refresh access token.', null=True),
        ),
    ]
