# Generated by Django 2.2.6 on 2019-11-22 19:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('redditors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrg',
            fields=[
                ('redditor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client_org', serialize=False, to='redditors.Redditor')),
                ('timestamp_client_connected', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_client_disconnected', models.DateTimeField(null=True)),
                ('last_time_client_request', models.DateTimeField(null=True)),
                ('last_time_client_updated', models.DateTimeField(null=True)),
                ('reddit_token', encrypted_model_fields.fields.EncryptedCharField(help_text='Reddit refresh token for the Salesforce Client Org.')),
                ('client_token', encrypted_model_fields.fields.EncryptedCharField(help_text='Generated random token for Salesforce Client Org.')),
            ],
            options={
                'ordering': ['timestamp_client_connected'],
            },
        ),
        migrations.CreateModel(
            name='SalesforceOrg',
            fields=[
                ('org_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=256)),
                ('org_url', models.URLField(max_length=512)),
                ('package_version', models.CharField(blank=True, default='1.0', max_length=8)),
            ],
            options={
                'ordering': ['org_name'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('client_org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='accounts.ClientOrg', verbose_name='Client Org')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clientorg',
            name='salesforce_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.SalesforceOrg'),
        ),
    ]
