# Generated by Django 2.2.6 on 2019-11-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191124_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
